<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/sample.proto

namespace GPBMetadata\Src;

class Sample
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6010a107372632f73616d706c652e70726f746f12076578616d706c65" .
            "221e0a0b4563686f52657175657374120f0a076d65737361676518012001" .
            "2809221f0a0c4563686f526573706f6e7365120f0a076d65737361676518" .
            "012001280932400a074578616d706c6512350a044563686f12142e657861" .
            "6d706c652e4563686f526571756573741a152e6578616d706c652e456368" .
            "6f526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

