<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/sample.proto

namespace GPBMetadata\Src;

class Sample
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4010a107372632f73616d706c652e70726f746f120773657276696365" .
            "22270a17436f6e7472697665644d65737361676552657175657374120c0a" .
            "04626f647918012001280922280a18436f6e7472697665644d6573736167" .
            "65526573706f6e7365120c0a04626f6479180120012809326c0a10436f6e" .
            "7472697665645365727669636512580a0f436f6e7472697665644d657468" .
            "6f6412202e736572766963652e436f6e7472697665644d65737361676552" .
            "6571756573741a212e736572766963652e436f6e7472697665644d657373" .
            "616765526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

