<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: src/sample.proto

namespace Example;

use Spiral\GRPC;

interface ExampleInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "example.Example";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param EchoRequest $in
    * @return EchoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Echo(GRPC\ContextInterface $ctx, EchoRequest $in): EchoResponse;
}
